# Generated by Django 4.1.10 on 2023-09-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_accepted',
            field=models.BooleanField(default=False, help_text="Designates whether this user's site registration has been accepted."),
        ),
    ]
