# Generated by Django 4.1.10 on 2023-09-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_registration_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_accepted',
            field=models.BooleanField(default=False, help_text="Designates whether this user's site registration has been accepted.", verbose_name='Registration Accepted'),
        ),
    ]
